version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: RAG
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mini1234
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata2: